[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AlteryxGalleryAPI"
version = "0.0.7"
authors = [
  { name="PAUL HOUGHTON",  email="paul.houghton@theinformationlab.co.uk"},
]
description = "An API for connecting to an Alteryx Gallery. Forked from the project by DAVID PRYOR, NICK SIMMONS, AND RITU GOWLIKAR"
readme = "README.md"
requires-python = ">=3.8, <3.12"
license = {file = "LICENSE"}
classifiers = [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Development Status :: 3 - Alpha",  
                "Programming Language :: Python :: 3.8",
                "Programming Language :: Python :: 3.9",
                "Programming Language :: Python :: 3.10",
                "Programming Language :: Python :: 3.11",
                "Audience :: Developers",
                "Topic :: Utilities",
]
dependencies = [
        "requests",
        ]

[project.urls]
"API Documentation" = "https://gallery.alteryx.com/api-docs/"
"Source" = "https://github.com/Sivivatu/AlteryxGalleryAPI"
"Bug Tracker" = "https://github.com/Sivivatu/AlteryxGalleryAPI/issues"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
log_cli_level = "info"
testpaths = [
    "src",
]
