

# TODO: package building process needs to be migrated to uv
# repository = "https://github.com/Sivivatu/AlteryxGalleryAPI"
# keywords = ["Alteryx Server", "Atleryx Gallery", "API", "Alteryx Gallery API", "Alteryx Server API", "Alteryx API"]

# [tool.poetry.urls]
# "API Documentation" = "https://help.alteryx.com/current/en/server/api-overview/alteryx-server-api-v3.html"
# "Bug Tracker" = "https://github.com/Sivivatu/AlteryxGalleryAPI/issues"


# # TODO: package building process needs to be migrated to uv
# [build-system]
# requires = ["poetry-core"]
# build-backend = "poetry.core.masonry.api"
