name: Python Package using Poetry

on: pull_request

jobs:
  poetry_linting:
    strategy:
      fail-fast: true
      matrix:
        python-version:  ["3.10"]
        poetry-version: ["1.8.2"]
        os: [ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Lint with ruff
        run: |
          poetry run ruff check
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run ruff format . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


  poetry_targeted_test:
    strategy:
      fail-fast: true
      matrix:
        python-version:  ["3.10"]
        poetry-version: ["1.8.2"]
        os: [ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        env:
          HOST_URL: ${{ secrets.HOST_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TEST_OWNER_ID: ${{ secrets.TEST_OWNER_ID }}
        run: poetry run pytest
      

# jobs:
#   build-linux:
#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 5

#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python 3.11
#       uses: actions/setup-python@v3
#       with:
#         python-version: '3.11'
#     - name: Add conda to system path
#       run: |
#         # $CONDA is an environment variable pointing to the root of the miniconda directory
#         echo $CONDA/bin >> $GITHUB_PATH
#     - name: Install dependencies
#       run: |
#         conda env update --file environment.yml --name base
#     - name: Lint with flake8
#       run: |
#         conda install flake8
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#     - name: Test with pytest
#       run: |
#         conda install pytest
#         pytest
